services:
  db:
    image: postgres:latest
    container_name: postgres_db_todo
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"

  environment:
    - DEBUG

  envfile:
    - .env
# 永続化用のボリュームを定義
volumes:
  pg_data:
