"""create tables

Revision ID: 2ce8c6baddee
Revises: eb4220adba63
Create Date: 2024-10-30 11:40:55.452101

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2ce8c6baddee"
down_revision: Union[str, None] = "eb4220adba63"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("todoLists", sa.Column("limit_at", sa.DateTime(), nullable=True))
    op.create_index(
        op.f("ix_todoLists_limit_at"), "todoLists", ["limit_at"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_todoLists_limit_at"), table_name="todoLists")
    op.drop_column("todoLists", "limit_at")
    # ### end Alembic commands ###
