"""change tables

Revision ID: 784711dceffc
Revises: 880bfb7b60b6
Create Date: 2024-10-29 10:14:57.512575

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '784711dceffc'
down_revision: Union[str, None] = '880bfb7b60b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todoLists', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.create_index(op.f('ix_todoLists_updated_at'), 'todoLists', ['updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_todoLists_updated_at'), table_name='todoLists')
    op.drop_column('todoLists', 'updated_at')
    # ### end Alembic commands ###
