"""change tables

Revision ID: 880bfb7b60b6
Revises: 3b72213e6f84
Create Date: 2024-10-29 10:14:44.765075

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '880bfb7b60b6'
down_revision: Union[str, None] = '3b72213e6f84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_todoLists_updated_at', table_name='todoLists')
    op.drop_column('todoLists', 'updated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todoLists', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.create_index('ix_todoLists_updated_at', 'todoLists', ['updated_at'], unique=False)
    # ### end Alembic commands ###
